### ISSUE TITLE
Python 

### ISSUE THREAD

**Issue by klkr3580** [klkr3580/Bhavya-Sree-Kalikiri#1]
Wanna start a group of python developers to build a project..!

**Comment by hamzamujeebk** [comment]
Do you have any product Idea?

**Comment by klkr3580** [comment]
Are you interested ?

**Comment by hamzamujeebk** [comment]
I'm all ears.

**Comment by Frezo23** [comment]
i can try

**Comment by cyberpsychofc** [comment]
I'm interested. @klkr3580 How many members are you planning to have on the team and what's the project about???

**Comment by ecargsid-eht** [comment]
I'm interested too. I'm not a pro but I'd like to learn more about developing. I have learnt python  and some concepts of django. You can check my profile too.

**Comment by Harsh8833** [comment]
I'm also interested you can add me too.

**Comment by abhi12cool** [comment]
I am interested.

**Comment by akhil-006** [comment]
@klkr3580 I am interested too

**Comment by ghost** [comment]
I am also intrested but what are we building

**Comment by Tkailaine** [comment]
I am interested!
